# Generated by Django 2.2.7 on 2019-11-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TapSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('word', models.CharField(blank=True, default='', max_length=30)),
                ('paragraph', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
