# Generated by Django 2.2.7 on 2019-11-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tapsearch',
            options={},
        ),
        migrations.RemoveField(
            model_name='tapsearch',
            name='created',
        ),
    ]
