# Generated by Django 2.2.7 on 2019-11-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20191122_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TapSearch',
            new_name='Search',
        ),
    ]
