# Generated by Django 2.2.7 on 2019-11-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20191122_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='paragraph',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
    ]
